---
platform_environment: staging
application_environment: staging
aws_region: ap-south-1
ansible_connection: amazon.aws.aws_ssm
ansible_aws_ssm_region: "{{ aws_region }}"
ansible_aws_ssm_bucket_name: "{{ lookup('env', 'ANSIBLE_SSM_BUCKET') }}"
ansible_aws_ssm_bucket_sse_mode: aws:kms
ansible_aws_ssm_bucket_sse_kms_key_id: "{{ lookup('env', 'ANSIBLE_SSM_KMS_KEY') }}"
ansible_aws_ssm_s3_addressing_style: virtual
ansible_python_interpreter: /usr/bin/python3
ansible_become: true
