---
plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1
filters:
  tag:Project: secureops
  tag:Environment: dev
  instance-state-name: running
hostnames:
  - instance-id
keyed_groups:
  - key: tags.Role
    prefix: role
compose:
  ansible_host: instance_id
