[SERVICE]
    Flush 5
    Log_Level info
    Parsers_File parsers-custom.conf
    storage.path /fluent-bit/state/buffer
    storage.backlog.mem_limit 32M
[INPUT]
    Name tail
    Tag containers
    Path /var/lib/docker/containers/*/*-json.log
    Parser docker_json
    DB /fluent-bit/state/docker.db
    Mem_Buf_Limit 32MB
    Skip_Long_Lines On
    storage.type filesystem
[INPUT]
    Name tail
    Tag system
    Path /var/log/host/syslog,/var/log/host/messages,/var/log/host/auth.log
    DB /fluent-bit/state/system.db
    Skip_Long_Lines On
[FILTER]
    Name parser
    Match containers
    Key_Name log
    Parser app_json
    Reserve_Data On
[OUTPUT]
    Name opensearch
    Match *
    Host opensearch
    Port 9200
    Logstash_Format On
    Logstash_Prefix secureops
    Suppress_Type_Name On
    Generate_ID On
    Retry_Limit False
    storage.total_limit_size 1G
